name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 9 */5 * *'
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Consulta de Actividad a Supabase
        run: |
          curl -v -X GET "https://mkqymfnsommkvsppokmy.supabase.co/rest/v1/gastos?select=id&limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
